# Generated by Django 5.2.12 on 2026-09-18 06:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0005_alter_attendance_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=100)),
                ('status', models.CharField(default='Absent', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('attendance_time', models.DateTimeField(blank=True, null=True)),
                ('period_1', models.CharField(default='Absent', max_length=20)),
                ('period_2', models.CharField(default='Absent', max_length=20)),
                ('period_3', models.CharField(default='Absent', max_length=20)),
                ('period_4', models.CharField(default='Absent', max_length=20)),
                ('period_5', models.CharField(default='Absent', max_length=20)),
                ('period_6', models.CharField(default='Absent', max_length=20)),
                ('period_7', models.CharField(default='Absent', max_length=20)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student_id', 'date'), name='unique_daily_student_attendance')],
            },
        ),
    ]
