# Generated by Django 5.2.12 on 2026-09-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0007_copy_legacy_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='roll_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
