# Generated by Django 5.2.12 on 2026-09-18 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0010_fix_case_insensitive_roll_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
