# Generated by Django 5.2.12 on 2026-09-18 07:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0011_delete_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyattendance',
            name='period_4',
        ),
        migrations.RemoveField(
            model_name='dailyattendance',
            name='period_5',
        ),
        migrations.RemoveField(
            model_name='dailyattendance',
            name='period_6',
        ),
        migrations.RemoveField(
            model_name='dailyattendance',
            name='period_7',
        ),
        migrations.CreateModel(
            name='StudentFaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='face_images/%Y/%m/%d')),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_images', to='Students.userprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'image'), name='unique_student_face_image')],
            },
        ),
    ]
